### ISSUE TITLE
Use Object.observe

### ISSUE THREAD

**Issue by Hypercubed** [curran/model#9]
_We discussed this previously but I'm adding this here for tracking my suggestion._

I think model-js should consider using ES7 Object.observe rather than property setters.  One complication is that Object.observe performs callbacks on the next animation frame (pooling changes) whereas model-js calls the callbacks immediately when the property changes.

Object.observe is already implemented in v8 however they are looking into [a memory leak](https://code.google.com/p/v8/issues/detail?id=3328&q=Object.observe&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Area%20Stars).

**Comment by curran** [comment]
I agree that it would be awesome to try using Object.observe. It would make the library even simpler!

**Comment by Hypercubed** [comment]
I forgot to include the link to my experimental model-js using Object.observe.  https://github.com/Hypercubed/model/blob/experimental/src/model.js

**Comment by Hypercubed** [comment]
FYI...  https://esdiscuss.org/topic/an-update-on-object-observe

**Comment by curran** [comment]
Interesting, thanks for the update. Since Object.observe is pretty much abandoned, I think I'll close this issue.
